version: "3"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis-test
    networks:
      - first-network
    environment:
      - REDIS_PASSWORD=cibilex
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      - redis-test:/bitnami/redis/data
  app:
    container_name: my-app
    build:
      context: .
    networks:
      - first-network
    environment:
      - HOST=redis-test
    depends_on:
      - redis
    ports:
      - "8080:8080"
networks:
  first-network:
volumes:
  redis-test:
